version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak:
    depends_on:
      - keycloak-db
    image: quay.io/keycloak/keycloak:15.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USER: admin
      DB_PASSWORD: password
    ports:
      - "8000:8080"
    restart: unless-stopped

  keycloak-db:
    image: postgres:13
    container_name: keycloak-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432"
    volumes:
      - kc-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
  kc-db-data:
