port: 3000
oauth2:
  keycloak-url: http://localhost:8000/auth/realms/timepicker
  client-id: timepicker-app
  callback-uri: http://localhost:8080/auth/callback
  redirect-uri: http://localhost:8080/auth

postgres:
  host: localhost
  port: 5432
  db: postgres
